title: Umbrella Analytics
email: info@umbrellaanalytics.net
description: >- # this means to ignore newlines until "baseurl:"
  Diversity and Inclusion Analytics. Improve diversity and inclusion in your workplace using data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.umbrellaanalytics.net"

plugins:
  - jekyll-gzip

sass:
  load_paths:
    - _sass
    - node_modules/

# Disable CORS in development
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
